menu:
    Blog: /
    RSS: /atom.xml
    Github: https://github.com/JunyuMu
    Twitter: https://twitter.com/mujunyu
    Mail: mailto:mujunyu@mujunyu.com

favicon: /img/favicon.png
logo: /img/log.png

# google-analytics:
ga: UA-67842727-1

# disqus
disqus: junyu