menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/kozzzx
    GitHub: https://github.com/kozzzx
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: lolila

# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2015