menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/kozzzx
    GitHub: https://github.com/kozzzx
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
# e.g duoshuo: seansun (if your duoshuo's subdomain is seansun.duoshuo.com) 
disqus:
duoshuo: lolila

# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2015

# 备案号 Chinese ICP license
beian: 